[package]
name = "argus"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
